theme: jekyll-theme-minimal
title: Ehab site
description: A short description of my work
how_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
